### ISSUE TITLE
Path is Already Configured for Another Movie

### ISSUE THREAD

**Issue by SalmonSays** [v0idp/Mellow#118] opened 2020-03-09 19:24 UTC
So I noticed a problem that seems to be Mellow specific-

I have a desire to create 2 entries in Radarr for a movie called Shoot to Kill, one is from 1947 and the second is from 1988. Adding Shoot to Kill (1947) works fine and sets a path inside Radarr labeled "Shoot to Kill". Adding the second 1988 version spits out "Path is already configured for another movie"

The reason I suggest it's mellow specific is adding the same movie inside Radarr properly configures the second path to "Shoot to Kill (1988)"

{
  error: null,
  body: '[\r\n' +
    '  {\r\n' +
    '    "propertyName": "Path",\r\n' +
    '    "errorMessage": "Path is already configured for another movie",\r\n' +
    '    "attemptedValue": "P:\\\\Plex Movies\\\\Shoot to Kill",\r\n' +
    '    "formattedMessageArguments": [],\r\n' +
    '    "formattedMessagePlaceholderValues": {\r\n' +
    '      "propertyName": "Path",\r\n' +
    '      "propertyValue": "P:\\\\Plex Movies\\\\Shoot to Kill"\r\n' +
    '    }\r\n' +
    '  }\r\n' +
    ']'
}

**Comment by v0idp** [comment] 2020-03-10 21:36
sorry, my bad. I totally forgot that this issue is a duplicate of: #115

**Closed as completed by v0idp** 2020-03-10 21:36 UTC

**Comment by v0idp** [comment] 2020-03-14 16:48
Fixed in 07aa1bee
