### ISSUE TITLE
[Feature request] Add commands to call some Tautulli stats into Discord like Top Movies / Top Shows/ Top users

### ISSUE THREAD

**Issue by SuissoNaBisso9** [v0idp/Mellow#103] opened 2020-02-14 12:48 UTC
Hey

thanks for the work done already, Mellow is fantastic tool !
Would be great to add as well some commands to get Tautulli stats into Discord such as :

- Most watched movies / Most popular movies

- Most watched TV shows / Most Popular TV shows

- Most active users

- Most active platforms

- Current streams (with transcode / direct split)

And finally is there is any way to schedule these on a daily / weekly / monthly basis would be awesome !

Thanks

**Comment by v0idp** [comment] 2020-02-14 12:51
duplicate of #73

**Closed as completed by v0idp** 2020-02-14 12:51 UTC
Labels: Duplicate
